steps:
  # ==========================================
  # PRODUCT APP (Next.js in Root)
  # ==========================================
  # 1. Build the Product Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-product:$_COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-product:latest'
      - '.'
    id: 'build-product-image'

  # 2. Push the Product Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/sheersdigital-product'
    id: 'push-product-image'

  # 3. Deploy Product to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sheersdigital-product'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sheersdigital-product:$_COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
    id: 'deploy-product-cloud-run'

  # ==========================================
  # BUSINESS WEBSITE (Vite/React in /business-website)
  # ==========================================
  # 4. Build the Website Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'business-website'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:$_COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:latest'
      - '.'
    id: 'build-website-image'

  # 5. Push the Website Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site'
    id: 'push-website-image'

  # 6. Deploy Website to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sheersdigital-site'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sheersdigital-site:$_COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
    id: 'deploy-website-cloud-run'

images:
  - 'gcr.io/$PROJECT_ID/sheersdigital-product:$_COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sheersdigital-product:latest'
  - 'gcr.io/$PROJECT_ID/sheersdigital-site:$_COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sheersdigital-site:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '2400s'

